apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oz5lt8r5d-nodejs 
  janus-idp.io/tekton: oz5lt8r5d-nodejs
  backstage.io/kubernetes-id: oz5lt8r5d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oz5lt8r5d-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  